services:
  app_blue:
    image: ${BLUE_IMAGE}
    environment:
      - PORT=3000
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - APP_POOL=blue
    ports:
      - "8081:3000"

  app_green:
    image: ${GREEN_IMAGE}
    environment:
      - PORT=3000
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - APP_POOL=green
    ports:
      - "8082:3000"

  nginx:
    image: nginx:stable
    depends_on:
      - app_blue
      - app_green
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

